name: context-var-demo
on: push

jobs:
 contect:
  runs-on: ubuntu-latest
  steps:
   - name: calling context variable
     run: |
      echo "Repository name is ${{ github.repository }}"
      echo "branch is ${ github.ref }}"
      echo "User account name is ${{ github.actor }}"
     
     
