name: inputs-demo
on: 
  workflow_dispatch:
   inputs:
     name:
      description: choose the environment to deploy
      default: develop
      required: true
      type: choice
      options:
        - dev
        - test
        - prod

jobs:
 inputs-demo:   
   runs-on: ubuntu-latest
   steps:
    - name: Calling Input values
      run: echo "Deployed application in ${{inputs.name}}"
